# Generated by Django 3.1.1 on 2020-11-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='suggested_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
