# Generated by Django 3.1.1 on 2020-11-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0003_people_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
