# Generated by Django 3.1.1 on 2020-11-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0004_auto_20201116_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='restltform.follow'),
        ),
    ]
