# Generated by Django 3.1.1 on 2020-11-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0005_auto_20201116_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
