# Generated by Django 3.1.1 on 2020-11-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0006_auto_20201116_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
