# Generated by Django 3.1.1 on 2020-11-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0007_auto_20201116_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='suggested_tag',
            field=models.TextField(blank=True, default='running', null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='follow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='restltform.follow'),
        ),
    ]
