# Generated by Django 3.1.1 on 2020-11-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restltform', '0012_auto_20201121_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
